webtalk_init -webtalk_dir H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.sim/sim_1/behav/xsim/xsim.dir/convolution_componet_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 22 15:27:24 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "11ef7f4b-a094-45a2-b98c-143cfffb3ec1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "346904a4b4e64b0bad82b581b8b9d543" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2397 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "52655985 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "26.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14648_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2618776482 -regid "" -xml H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.sim/sim_1/behav/xsim/xsim.dir/convolution_componet_test_behav/webtalk/usage_statistics_ext_xsim.xml -html H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.sim/sim_1/behav/xsim/xsim.dir/convolution_componet_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.sim/sim_1/behav/xsim/xsim.dir/convolution_componet_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
