# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/median.xdc

# IP: ip/uartlite/uartlite.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uartlite || ORIG_REF_NAME==uartlite} -quiet] -quiet

# IP: ip/padd_ram/padd_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==padd_ram || ORIG_REF_NAME==padd_ram} -quiet] -quiet

# IP: ip/io_ram/io_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==io_ram || ORIG_REF_NAME==io_ram} -quiet] -quiet

# XDC: ip/uartlite/uartlite_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite || ORIG_REF_NAME==uartlite} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/uartlite/uartlite_ooc.xdc

# XDC: ip/uartlite/uartlite.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite || ORIG_REF_NAME==uartlite} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/padd_ram/padd_ram_ooc.xdc

# XDC: ip/io_ram/io_ram_ooc.xdc
