# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.cache/wt [current_project]
set_property parent.project_path H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo h:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files f:/coeConcerte/d60test.coe
add_files f:/coeConcerte/padded60.coe
read_vhdl -library xil_defaultlib {
  H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/new/convolution_component.vhd
  H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/new/kernel_component.vhd
  H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/new/padding_component.vhd
  H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/new/signal_selection_component.vhd
  H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/new/sort_component.vhd
  H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/new/state_control_component.vhd
  H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/new/uart_commi_component.vhd
  H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/new/main_component.vhd
}
read_ip -quiet H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/ip/uartlite/uartlite.xci
set_property used_in_implementation false [get_files -all h:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/ip/uartlite/uartlite_board.xdc]
set_property used_in_implementation false [get_files -all h:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/ip/uartlite/uartlite_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/ip/uartlite/uartlite.xdc]

read_ip -quiet H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/ip/padd_ram/padd_ram.xci
set_property used_in_implementation false [get_files -all h:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/ip/padd_ram/padd_ram_ooc.xdc]

read_ip -quiet H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/ip/io_ram/io_ram.xci
set_property used_in_implementation false [get_files -all h:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/sources_1/ip/io_ram/io_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/constrs_1/new/median.xdc
set_property used_in_implementation false [get_files H:/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.srcs/constrs_1/new/median.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main_component -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main_component.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_component_utilization_synth.rpt -pb main_component_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
