webtalk_init -webtalk_dir F:/Semester 7/HDL/project/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.sim/sim_1/behav/xsim/xsim.dir/sort_componet_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 22 09:58:45 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "65044573-fc25-4507-bfb9-c888f9e5ecc9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "346904a4b4e64b0bad82b581b8b9d543" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5796_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3129608258 -regid "" -xml F:/Semester 7/HDL/project/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.sim/sim_1/behav/xsim/xsim.dir/sort_componet_test_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Semester 7/HDL/project/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.sim/sim_1/behav/xsim/xsim.dir/sort_componet_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Semester 7/HDL/project/Median_Filter_For_SandPNoice/Median_Filter_For_SandPNoice.sim/sim_1/behav/xsim/xsim.dir/sort_componet_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
